[project]
name = "sapat"
version = "0.1.2"
description = "Video Transcription Tool using different APIs"
requires-python = ">=3.6"
dependencies = [
    "click>=8.1.8",
    "requests>=2.32.3",
    "python-dotenv>=1.0.1",
    "openai>=1.58.1",
    "groq>=0.13.1",
    "replicate>=1.0.0"
]

[project.scripts]
sapat = "sapat.script:main"

[build-system]
requires = ["wheel", "setuptools>=61.0"] # Ensure setuptools is recent enough
build-backend = "setuptools.build_meta"
